Add missing httpcore lib that lead to errors
Errors on Java 1_5

== Appaloosa Client V1.10
== Deploy file /tmp/jenkins3831893635757004548temp-appaloosa-deploy.apk to Appaloosa
== reseting http connection
== Ask for upload information
ERROR: Step ‘Upload to Appaloosa’ aborted due to exception:
java.lang.NoClassDefFoundError: org/apache/http/util/Args
at org.apache.http.conn.scheme.Scheme.<init>(Scheme.java:92)
at org.apache.http.impl.conn.SchemeRegistryFactory.createDefault(SchemeRegistryFactory.java:51)
at org.apache.http.impl.client.AbstractHttpClient.createClientConnectionManager(AbstractHttpClient.java:266)
at org.apache.http.impl.client.AbstractHttpClient.getConnectionManager(AbstractHttpClient.java:437)
at com.appaloosastore.client.AppaloosaClient.resetHttpConnection(AppaloosaClient.java:462)
at com.appaloosastore.client.AppaloosaClient.getUploadForm(AppaloosaClient.java:456)
at com.appaloosastore.client.AppaloosaClient.deployFile(AppaloosaClient.java:167)
at com.appaloosastore.client.AppaloosaClient.deployFile(AppaloosaClient.java:131)
at org.jenkins.plugins.appaloosa.AppaloosaPublisher.perform(AppaloosaPublisher.java:167)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
at hudson.model.Build$BuildExecution.post2(Build.java:186)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
at hudson.model.Run.execute(Run.java:1840)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:97)
at hudson.model.Executor.run(Executor.java:429)